# Generated by Django 4.1.5 on 2023-01-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="number",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="address",
            name="zip_code",
            field=models.CharField(max_length=8),
        ),
    ]
