# Generated by Django 4.1.5 on 2023-01-11 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donees", "0001_initial"),
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donee",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donees",
                to="institutions.institution",
            ),
        ),
    ]
