# Generated by Django 4.1.5 on 2023-01-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donees", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donee",
            name="institution",
        ),
    ]
