# Generated by Django 4.1.5 on 2023-01-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donees", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Disponível", "Disponivel"),
                            ("Não disponível", "Nao Disponivel"),
                            ("Enviado", "Enviado"),
                            ("Recebido", "Recebido"),
                            ("Não informado", "Not Informed"),
                        ],
                        default="Não informado",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitations",
                        to="donees.donee",
                    ),
                ),
            ],
        ),
    ]
