# Generated by Django 4.1.5 on 2023-01-11 15:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
        ("donees", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Disponível", "Disponivel"),
                            ("Não disponível", "Nao Disponivel"),
                            ("Enviado", "Enviado"),
                            ("Recebido", "Recebido"),
                            ("Não informado", "Not Informed"),
                            ("Desativado", "Disable"),
                        ],
                        default="Não informado",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitations",
                        to="donees.donee",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitations",
                        to="institutions.institution",
                    ),
                ),
            ],
        ),
    ]
