# Generated by Django 4.1.5 on 2023-01-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solicitations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Disponível", "Disponivel"),
                    ("Não disponível", "Nao Disponivel"),
                    ("Enviado", "Enviado"),
                    ("Recebido", "Recebido"),
                    ("Não informado", "Not Informed"),
                    ("Desativado", "Disable"),
                ],
                default="Não informado",
                max_length=20,
            ),
        ),
    ]
