# Generated by Django 4.0.7 on 2023-01-05 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donees', '0002_initial'),
        ('solicitations', '0003_alter_solicitation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='donee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitations', to='donees.donee'),
        ),
    ]
