# Generated by Django 4.1.5 on 2023-01-10 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_initial"),
        ("solicitations", "0005_alter_solicitation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitation",
            name="institution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitations",
                to="institutions.institution",
            ),
        ),
    ]
