# Generated by Django 4.1.5 on 2023-01-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pix_donation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pixdonation",
            name="value",
            field=models.CharField(max_length=8),
        ),
    ]
