# Generated by Django 4.1.5 on 2023-01-04 15:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("cnpj", models.IntegerField()),
                ("phone", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Orfanato", "Orfanato"),
                            ("Asilo", "Asilo"),
                            ("Não informado", "Not Informed"),
                        ],
                        default="Não informado",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution",
                        to="addresses.address",
                    ),
                ),
            ],
        ),
    ]
