# Generated by Django 4.1.5 on 2023-01-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="status",
            field=models.CharField(
                choices=[
                    ("Under examination", "Under Examination"),
                    ("Approved", "Approved"),
                ],
                default="Under examination",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="cnpj",
            field=models.IntegerField(unique=True),
        ),
    ]
