# Generated by Django 4.1.5 on 2023-01-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0003_institution_status_alter_institution_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="cnpj",
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
